# This file is released under the CC0 1.0 Universal (CC0 1.0) Public Domain Dedication.
# See the LICENSE.txt file or https://creativecommons.org/publicdomain/zero/1.0/ for details.

version: '3.8'
services:
  db:
    image: oracledb-with-utplsql
    build:
      context: .
      dockerfile: Dockerfile
      args:
        oracledb_repository: ${ORACLEDB_REPOSITORY:-oracle/database}
        oracledb_tag: ${ORACLEDB_TAG:?required}
        utplsql_version: ${UTPLSQL_VERSION:-latest}
    ports:
      - 1521:1521
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - ORACLE_PWD=mydatabasepassword
